### ISSUE TITLE
Esx_inventoryhud integration

### ISSUE THREAD

**Issue by CarlBishop** [yeganehha/gang#1]
Hi and sorry for the issue.

Is there a way to integrate the esx_inventoryhud interface when opening the armory or searching users?

I think this is not simple since the native sql interaction from inventoryhud search for datastore with gangs name...

maybe you can think about this even if this resouce is not related to any framework...

**Comment by yeganehha** [comment]
Hi
It must be developed in esx_inventoryhud and connected to this GANG system.
Because this script connects to variable cores, it is not possible to develop in these github repositories.

if you want this , you can open ticket in my own discord : https://discord.gg/W7Dxdmsnry
