### ISSUE TITLE
script:gang] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export executeSync in resource ghmattimysql

### ISSUE THREAD

**Issue by Moonlgiht111** [yeganehha/gang#11]
script:gang] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export executeSync in resource ghmattimysql

error spam

**Comment by yeganehha** [comment]
hello

please add this script: ghmattimysql
and start that before start gang

**Comment by Moonlgiht111** [comment]
I added it and it follows the same error, can you pass me the link to install a more updated one?
