### ISSUE TITLE
Can't see gang on server join

### ISSUE THREAD

**Issue by BTNGaming** [yeganehha/gang#7]
When joining the server after a reboot, or just logging out and coming back, you can no longer see or access gang blips or anything.

This happens both on server reboot, and on rejoining the server after you've joined the gang.

In order to fix it, an ADMIN has to go into /gangs and re-set the blip location and everything shows back up.

**Comment by AmirrezaJaberi** [comment]
Hi, 

Add this from **client/mian.lua**

`AddEventHandler("playerSpawned", function()`
	`TriggerServerEvent("Erfan:gang:getActiveGang")`
`end)`
