### ISSUE TITLE
Invalid Permission

### ISSUE THREAD

**Issue by TrueSunnyD** [yeganehha/gang#8]
Seems like everything works when following the steps. 

I also ensured I added my steam identifier hex where it asked me to.

When I am in game and do /gangs it says "Invalid Permission" 
Am I missing something else that I was supposed to add to give myself permission to access the /gangs?

**Comment by yeganehha** [comment]
please send part of server.cfg that import gang resource and config.lua

**Comment by cookieb43** [comment]
im also having this issue i placed this in my start config i havnt touched the config.lua

add_principal identifier.steam:110000105d78d98 group.gangManager
add_ace resource.gang command.add_ace allow
start gang

but i just get a Invalid Permission notification

**Comment by danammeansbear** [comment]
I am currently having this issue

**Comment by fusedesign** [comment]
same issue
